# Generated by Django 4.2.7 on 2023-12-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Batch',
            new_name='UploadBatch',
        ),
    ]
